[package]
name = "auth"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
actix-web = "0.7"
lazy_static = "1.2"
tera = "0.11"
serde = "1.0"
serde_derive = "1.0"
actix-web-httpauth = "0.1"
